language: cpp
before_install: sudo apt-get install cmake && sudo apt-get install gcc-4.8
jobs:
    include:
        - stage: gamelib
          name: "Game library"
          script: cd library && mkdir build && cd build && cmake .. && make
        - stage: tester
          name: "Tester"
          script: chmod +x builder.sh && ./builder.sh && ./tester.exe
stages:
    - gamelib
    - tester
